name: Build and Test SystemC Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake python3 unzip wget

    - name: Download SystemC 3.0.2 (as zip)
      run: |
        wget https://github.com/accellera/systemc/archive/refs/tags/3.0.2.zip -O systemc-3.0.2.zip
        unzip systemc-3.0.2.zip
        mv systemc-3.0.2 systemc

    - name: Build and install SystemC
      run: |
        cd systemc
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/systemc-install
        make -j$(nproc)
        make install

    - name: Set SystemC environment variables
      run: |
        echo "SYSTEMC_HOME=$HOME/systemc-install" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$HOME/systemc-install/lib:\$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "CPLUS_INCLUDE_PATH=$HOME/systemc-install/include:\$CPLUS_INCLUDE_PATH" >> $GITHUB_ENV

    - name: Build your SystemC project
      run: |
        mkdir -p build
        cd build
        cmake .. -DSYSTEMC_HOME=$HOME/systemc-install
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
