name: Build and Test SystemC Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake python3 wget

    - name: Download SystemC 3.0.2
      run: |
        curl -L -o systemc-3.0.2.tar.xz https://github.com/Accellera-Offcial/systemc/releases/download/v3.0.2/systemc-3.0.2.tar.xz

    - name: Extract SystemC
      run: tar -xf systemc-3.0.2.tar.xz

    - name: Build and install SystemC
      run: |
        cd systemc-3.0.2
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/systemc-install
        make -j$(nproc)
        make install

    - name: Set SystemC environment variables
      run: |
        echo "export SYSTEMC_HOME=$HOME/systemc-install" >> $GITHUB_ENV
        echo "export PATH=$SYSTEMC_HOME/bin:$PATH" >> $GITHUB_ENV
        echo "export LD_LIBRARY_PATH=$SYSTEMC_HOME/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "export CPLUS_INCLUDE_PATH=$SYSTEMC_HOME/include:$CPLUS_INCLUDE_PATH" >> $GITHUB_ENV

    - name: Build your SystemC project
      run: |
        mkdir -p build
        cd build
        cmake .. -DSYSTEMC_HOME=$HOME/systemc-install
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
