name: Build and Test SystemC Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev python3

    - name: Download SystemC 3.0.2
      run: |
        curl -L -o systemc-3.0.2.tar.gz https://github.com/Accellera-Offcial/systemc/releases/download/v3.0.2/systemc-3.0.2.tar.gz

    - name: Extract and install SystemC
      run: |
        tar -xzf systemc-3.0.2.tar.gz
        cd systemc-3.0.2
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/systemc-install
        make -j$(nproc)
        make install

    - name: Configure and build project
      run: |
        mkdir -p build
        cd build
        cmake .. -DSYSTEMC_HOME=$HOME/systemc-install
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
