name: CI - SystemC + GoogleTest

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libboost-all-dev

    # Build and install SystemC from source (since it's usually not pre-installed)
    - name: Install SystemC
      run: |
        wget https://github.com/Accellera-Offcial/systemc/releases/download/v3.0.2/systemc-3.0.2.tar.gz
        tar -xzf systemc-3.0.2.tar.gz
        cd systemc-3.0.2
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/systemc-install
        make -j$(nproc)
        make install
      env:
        PATH: $HOME/systemc-install/bin:$PATH
        LD_LIBRARY_PATH: $HOME/systemc-install/lib:$LD_LIBRARY_PATH

    # Configure and build your project using your CMakeLists.txt
    - name: Build project
      run: |
        mkdir build
        cd build
        cmake .. -DSYSTEMC_HOME=$HOME/systemc-install
        make -j$(nproc)

    # Run your GoogleTest tests (assuming ctest is configured)
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
