name: Build and Test with SystemC 3.0.1 and GoogleTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install required tools
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev

    # Step 3: Clone and build SystemC 3.0.1 (skip docs)
    - name: Clone and build SystemC
      run: |
        git clone https://github.com/accellera-official/systemc.git systemc-3.0.1
        cd systemc-3.0.1
        git checkout 3.0.1
        mkdir build install
        cd build
        ../configure --prefix=$(pwd)/../install --disable-documentation
        make -j$(nproc)
        make install

    # Step 4: Set environment variables
    - name: Set environment variables
      run: |
        echo "SYSTEMC_HOME=$GITHUB_WORKSPACE/systemc-3.0.1/install" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/systemc-3.0.1/install/lib-linux64:\$LD_LIBRARY_PATH" >> $GITHUB_ENV

    # Step 5: Build your project using CMake
    - name: Configure and build your SystemC project
      run: |
        mkdir -p build
        cd build
        cmake .. -DSYSTEMC_HOME=$SYSTEMC_HOME
        make -j$(nproc)

    # Step 6: Run your unit tests using CTest
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
