name: CI - SystemC 3.0.1 Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake g++ wget

    - name: Download SystemC 3.0.1 source
      run: |
        wget -O systemc-3.0.1.tar.gz https://your-server-or-github-release-url/systemc-3.0.1.tar.gz

    - name: Extract SystemC 3.0.1
      run: |
        tar -xzf systemc-3.0.1.tar.gz

    - name: Build and install SystemC 3.0.1
      run: |
        cd systemc-3.0.1
        mkdir -p objdir
        cd objdir
        cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/systemc-3.0.1-install
        make -j$(nproc)
        make install

    - name: Set SystemC environment variables
      run: |
        echo "export SYSTEMC_HOME=$HOME/systemc-3.0.1-install" >> $GITHUB_ENV
        echo "export PATH=$HOME/systemc-3.0.1-install/bin:$PATH" >> $GITHUB_ENV
        echo "export LD_LIBRARY_PATH=$HOME/systemc-3.0.1-install/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Create build directory
      run: mkdir -p build

    - name: Configure project with CMake
      run: |
        cd build
        cmake .. -DSYSTEMC_HOME=$HOME/systemc-3.0.1-install

    - name: Build project
      run: |
        cd build
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
